# Generated by Django 2.1.1 on 2018-10-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='empresa_solicitante',
            field=models.CharField(default='', max_length=100),
        ),
    ]
