# Generated by Django 2.1.1 on 2018-10-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0002_prestamo_empresa_solicitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='Intereses',
            field=models.DecimalField(decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='TCEA',
            field=models.DecimalField(decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='VAN',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='cuotas',
            field=models.DecimalField(decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='modelo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='vehiculo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
