# Generated by Django 2.1.1 on 2018-10-16 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0007_auto_20181014_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='empresa_solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leasing.Empresa'),
        ),
    ]
