# Generated by Django 2.1.1 on 2018-10-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0008_auto_20181016_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='tipo_de_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Crédito', 'Crédito')], default='Efectivo', max_length=6),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='tipo_tasa_interes',
            field=models.CharField(choices=[('TEA', 'TEA'), ('TNA', 'TNA')], default='TEA', max_length=20),
        ),
    ]
