# Generated by Django 2.1.1 on 2018-10-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0009_auto_20181016_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='empresa_solicitante',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='tipo_de_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Crédito', 'Crédito')], default='Efectivo', max_length=20),
        ),
    ]
