# Generated by Django 2.1.1 on 2018-10-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0011_auto_20181016_0839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='plazos_de_pago',
            new_name='frecuencia_de_pago',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='cuotas',
            new_name='numero_de_años',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='VAN',
            new_name='precio_venta_del_activo',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='TCEA',
            new_name='recompra',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='comision_rt',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='cuota_inicial',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='fotocopias',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='gastos_admin',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='precio_venta',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='seguro_desgravamen',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='comision_de_activacion',
            field=models.DecimalField(decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='comision_de_estudio',
            field=models.DecimalField(decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='comision_periodica',
            field=models.DecimalField(decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='costos_notariales',
            field=models.DecimalField(decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='costos_registrales',
            field=models.DecimalField(decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='tasacion',
            field=models.DecimalField(decimal_places=4, max_digits=9, null=True),
        ),
    ]
