# Generated by Django 2.1.1 on 2018-10-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0012_auto_20181016_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='precio_venta_del_activo',
            field=models.FloatField(null=True),
        ),
    ]
