# Generated by Django 2.1.1 on 2018-10-17 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0015_auto_20181016_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='date_posted',
            field=models.DateTimeField(default=datetime.date(2018, 10, 17)),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, default=datetime.date(2018, 10, 17)),
        ),
    ]
