# Generated by Django 2.1.1 on 2018-10-17 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0016_auto_20181017_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
