# Generated by Django 2.1.1 on 2018-10-17 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0017_auto_20181017_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
