# Generated by Django 2.1.1 on 2018-10-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0018_auto_20181017_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='frecuencia_de_pago',
            field=models.IntegerField(choices=[(30, 'Mensual'), (60, 'Bimestral'), (90, 'Trimestral'), (120, 'Cuatrimestral'), (180, 'Semestral')], default=30),
        ),
    ]
