# Generated by Django 2.1.1 on 2018-10-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0019_auto_20181019_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='plazo_de_gracia',
            field=models.IntegerField(choices=[(30, '1 mes'), (60, '2 meses'), (90, '3 meses'), (120, '4 meses'), (150, '5 meses'), (180, '6 meses')], default=30),
        ),
    ]
