# Generated by Django 2.1.1 on 2018-10-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0022_auto_20181020_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='TCEA',
            new_name='TCEA_fb',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='VAN',
            new_name='TCEA_fn',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='VAN_fb',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='VAN_fn',
            field=models.FloatField(null=True),
        ),
    ]
