# Generated by Django 2.1.1 on 2018-10-23 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0023_auto_20181023_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='TCEA_fb',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='TCEA_fn',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='VAN_fb',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='VAN_fn',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='cuotas',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='intereses',
        ),
    ]
