# Generated by Django 2.1.1 on 2018-10-23 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0024_auto_20181023_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='TEA',
            new_name='tasa_de_interes',
        ),
    ]
