# Generated by Django 2.1.1 on 2018-10-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0026_prestamo_periodo_inicial_pg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='periodo_inicial_pg',
            field=models.IntegerField(default=1),
        ),
    ]
