# Generated by Django 2.1.1 on 2018-10-25 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0031_auto_20181024_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='periodo_cap',
            field=models.CharField(choices=[(360, 'diaria'), (24, 'quincenal'), (12, 'mensual'), (6, 'bimestral'), (4, 'trimestral'), (3, 'cuatrimestral'), (2, 'semestral'), (1, 'anual')], default=360, max_length=360),
        ),
    ]
