# Generated by Django 2.1.1 on 2018-10-25 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0035_auto_20181024_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='periodo_cap',
            field=models.CharField(choices=[(0, 'sin plazo de gracia'), (30, '1 mes'), (60, '2 meses'), (90, '3 meses'), (120, '4 meses'), (150, '5 meses'), (180, '6 meses')], default=360, max_length=20),
        ),
    ]
