# Generated by Django 2.1.1 on 2018-11-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0041_auto_20181117_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='periodo_inicial_pg',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='plazo_de_gracia',
            field=models.IntegerField(choices=[(0, 'sin plazo de gracia'), (30, '1 mes'), (60, '2 meses'), (90, '3 meses'), (120, '4 meses'), (150, '5 meses'), (180, '6 meses')], default=0),
        ),
    ]
