# Generated by Django 2.1.1 on 2018-11-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0042_auto_20181117_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='numero_de_años',
            field=models.IntegerField(default=1),
        ),
    ]
